import 'package:freezed_annotation/freezed_annotation.dart';

part 'country_details.freezed.dart';
part 'country_details.g.dart'; // File generated by json_serializable

@freezed
abstract class CountryDetails with _$CountryDetails {
  const factory CountryDetails({
 
    // ignore: invalid_annotation_target
    @JsonKey(name: 'cca2', defaultValue: 'NA')
    required String code, 
    // ignore: invalid_annotation_target
    @JsonKey(name: 'name', fromJson: _nameFromJson, toJson: _nameToJson)
    required String name,
    
    // ignore: invalid_annotation_target
    @JsonKey(name: 'flags', fromJson: _flagFromJson, toJson: _flagToJson)
    required String flag,
    
    // ignore: invalid_annotation_target
    @JsonKey(fromJson: _numToInt, toJson: _intToNum)
    required int population,
    
    // ignore: invalid_annotation_target
    @JsonKey(name: 'capital', fromJson: _capitalFromJson, toJson: _capitalToJson)
    required String capital,
    
    required String region,
    required String subregion,
    
    // ignore: invalid_annotation_target
    @JsonKey(fromJson: _numToInt, toJson: _intToNum)
    required int area,
    
    required List<String> timezones,
  }) = _CountryDetails;

  // The 'fromJson' factory required by json_serializable
  factory CountryDetails.fromJson(Map<String, dynamic> json) => _$CountryDetailsFromJson(json);
}


int _numToInt(dynamic value) {
  return (value as num?)?.toInt() ?? 0;
}

num _intToNum(int value) => value;

String _nameFromJson(dynamic name) {
  return (name as Map<String, dynamic>?)?['common'] as String? ?? 'Unknown';
}

Map<String, dynamic> _nameToJson(String name) {
  return {'common': name};
}

String _flagFromJson(dynamic flags) {
  return (flags as Map<String, dynamic>?)?['png'] as String? ?? '';
}

Map<String, dynamic> _flagToJson(String flag) {
  return {'png': flag};
}

String _capitalFromJson(dynamic capitalRaw) {
  if (capitalRaw is List<dynamic> && capitalRaw.isNotEmpty) {
    return capitalRaw[0].toString();
  } else if (capitalRaw is String) {
    return capitalRaw;
  }
  return 'N/A';
}

List<String> _capitalToJson(String capital) {
  return [capital];
}